export default {
  'imageRoute' : '/en',
  'aboutUsSubject': 'Ybrain aims to create new values in healthcare through brain.',
  'aboutUsMission': `Ybrain aims to innovate healthcare through neuromodulation devices based on non-invasive technologies. We are developing innovative healthcare solutions that enables effective treatment, diagnosis, and management of patients with psychiatric disorders. With our technology, we provide better user experiences during treatment and reach out to more people who seek better quality of life.`,
  'aboutUsVision': `Ybrain creates new values through innovation. Our innovative healthcare solutions that monitor, analyze, and further enhance the patient’s brain functions have been developed on the strong foundation of neuroscience, bio-medical engineering, electrical engineering, and computer science. We believe collaboration is the most effective way to breakthrough innovation that can create true values. Ybrain's company culture, progress through collaboration, reflects the way we work. `,
  'history1subject': 'Brain Region Associated with Depression',
  'history1content': 'It is clinically proven that a prefrontal cortex, located under the forehead, is associated with depression symptoms, especially with hyperactivity of amygdala; the emotion center.',
  'history2subject': 'Effects of Electric Stimulation on the Brain',
  'history2content': 'In the ancient western civilizations, electric brain stimulation techniques using electric eels and other natural sources were believed as a remedy for migraine and other disorders.',
  'history3subject': 'Non-Pharmaceutical Therapy Using Electric Stimulation',
  'history3content': `In the recent decades, the efficacy of brain stimulation has been well proven with advances in neuroscience including neuromodulation, neuroimaging, and other techniques such as Transcranial Magnetic Stimulation (TMS), transcranial Direct Current Stimulation (tDCS), functional Magnetic Resonance Imaging (fMRI), Positron Emission Tomography (PET), and Electroencephalography (EEG).
  
  Based on the scientific basis, YBRAIN demonstrated that MINDD can be effective for depression treatment.`,

  'technologMechanismySubject1': 'What Is Depression?',
  'technologMechanismyContents1': 'Patients with severe depression:',
  'technologMechanismyContents2-1': '"In the really darkness, the ankles are caught in chains,',
  'technologMechanismyContents2-2': 'It seems to hang on to the fear of the body which seems to be putting down',
  'technologMechanismyContents2-3': 'by hanging a giant pipe in the chest.',
  'technologMechanismyContents3': 'Symptoms associated with depression not only interfere with basic life such as loss of appetite or libido, but also affect cognitive abilities such as memory or concentration loss, and deterioration of physical functions such as hormonal and immune system imbalances.',
  'technologMechanismyContents4': 'Depression is not only associated with emotional abnormalities such as significant changes in mood, appetite, and libido but also affects cognitive and physical capabilities such as memory, cognition, and immune dysfunctions.',
  'technologMechanismyContents5': 'These abnormalities, that significantly affect daily livelihoods of the patients, are known to be due to the following biological factors.',
  'technologMechanismySubject2': '•	Biochemical – Environmental causes ',
  'technologMechanismyContents6': ': Abnormalities in maintaining balances in brain homeostasis and hormones',
  'technologMechanismySubject3': '•	Problem in Neurotransmitter Control',
  'technologMechanismyContents7': ': Abnormalities in managing brain function and emotion control',
  'technologMechanismySubject4': '• Asymmetry of left and right prefrontal cortex',
  'technologMechanismyContents8': ': Abnormalities in managing stress and uncomfortable situation',
  'technologMechanismySubject5': '• Hyperactivity of anterior cingulate cortex and amygdala',
  'technologMechanismyContents9': ': Abnormalities in emotion control',
  'technologMechanismySubject6': '• Depression Treatment',
  'technologMechanismyContents10': ': Abnormalities in sleep and memory',
  'technologMechanismySubject7': 'Depression Treatment',
  'technologMechanismyContents11': 'It is important to start treatment as early as possible before depression evolves tobecomes a chronic stage. ',
  'technologMechanismyContents12': 'Discuss with your families and/or mental health specialists to start a depression treatment. The specialists can provide the most suitable treatment options depending on the status of your depression.',
  'technologMechanismyContents13': '• 	Biological',
  'technologMechanismyContents14': '• 	Focus on brain hormonal balance',
  'technologMechanismyContents15': '• 	Psychological',
  'technologMechanismyContents16': '• 	Relief in psychological and	social issues',
  'technologMechanismyContents17': '• 	Neurophysiological',
  'technologMechanismyContents18': '• 	Focus on abnormal neuronal activity',
  'technologMechanismyContents19': 'Localized brain stimulation therapy with subtle current stimulation can compensate for the limitations of the efficacy limitations and side effects of existing therapies and allow for more treatment options.',
  'technologyCiraContents1': '•    Automatic detection of skin contact',
  'technologyCiraContents2': '•    Continuous impedance monitoring',
  'technologyCiraContents3': '•    Prescription and compliance management system',

  'productPurposeSubject1': 'MINDD for Depression Treatment',
  'productPurposeContents1': 'MINDD, a medical device based on tDCS (Transcranial Direct Current Stimulation), is developed to treat depressive symptoms of those patients with Major Depressive Disorder (MDD) by applying a weak current through a wearable module.',
  'productPurposeContents2': 'MINDD is a class III medical device in South Korea and a class II medical device in Europe.',
  'productPurposeSubject2': 'Better Treatment for Patients',
  'productPurposeContents3': 'We always explore better treatment options for patients by collaborating with medical professionals ',
  'productPurposeContents4': 'and investing in research and development.',
  'productEsSubject1': 'Efficacy and Safety',
  'productEsContents1': 'MINDD is the result of more than 5 years of advanced research and development, it has been designed, developed, manufactured, and tested in South Korea. Additional contribution has been developed in the US. In 2017 MINDD received the CE mark certification for medical device. The efficacy and safety of MINDD has been successfully proven in one of the largest multi-centered clinical trial in depression treatment using transcranial electric stimulation and also in other clinical trials in mild cognitive impairment, schizophrenia, addiction, ADHD, PTSD, and post-stroke rehabilitation.',
  'productEsSubject2': 'Reliability',
  'productEsContents2': 'In recent decades, transcranial electric stimulation technology has been one of the most promising brain stimulation technique in the clinical research sector. Based on this technology, MINDD has been engineered by an interdisciplinary team of neuroscientists, medical professionals, biomedical engineers, materials scientist, and software engineers and its efficacy and safety has been proven by major hospitals with thousands of treatment sessions in 10+ clinical trials. ',
  'productUseLegal': '※ This product is "medical equipment", "Precautions" and "how to use" Please read carefully. (License number: No. 17-135)',

}
