export default {
  'imageRoute' : '',
  'aboutUsSubject': '와이브레인이 뇌 과학을 통해 혁신하고자 하는 방향입니다.',
  'aboutUsMission': '와이브레인은 뇌 과학을 통해서 헬스케어 혁신을 이루고자 합니다.우리는 정신질환 환자들을 위한 치료, 진단, 관리를 모두 포함하는 헬스케어 솔루션을 개발하고 있습니다. 우리가 가진 기술로 더 많은 환자들의 일상의 질을 개선하고, 치료기간동안 더 나은 경험을 제공하고자 합니다.',
  'aboutUsVision': `우리는 혁신을 통해서 가치를 창출합니다. 신경과학, 기기개발, 컴퓨터 공학등 다양한 분야를 기반으로 언제 어디서나 환자들의 뇌 기능 상태를 분석, 저장, 강화, 관리하는 혁신적인 솔루션을 개발합니다. 우리는 협력을 통해 진보함으로써 우리가 이루고자 하는 가치를 창출해냅니다. 와이브레인이 가진 기업문화, 즉 협력을 통한 진보는 모두 회사 구성원들과 Ybrain의 파트너에 위한 것이며 그것이 우리가 함께 일하는 방식입니다.`,
  'history1subject': '우울증의 원인이 되는 부위',
  'history1content': '다수의 임상 연구와 의학계의 보고에 따르면 우리 머리 이마쪽에 있는 뇌 부위, 전두엽의 기능 저하가 우울증을 일으키는 주요 원인 중의 하나임이 과학적으로 밝혀졌습니다.',
  'history2subject': '미세한 전류 자극의 효과',
  'history2content': '우리의 뇌 부위에 흘려보내는 미세한 전류자극의 효과는 이집트와 그리스 같은 고대 유럽권 문명에서도 자주 언급된 기술입니다. 이전에는 전기 뱀장어와 같은 자연적인 소재를 통해 전기를 적용했고, 이를 두통과 같은 질환에 치료 목적으로 사용되었던 사례들도 고대 문헌에 언급되어 왔습니다.',
  'history3subject': '전기적 비약물요법으로 하는 우울증 치료',
  'history3content': `근래의 과학 발전과 함께 1800년대부터 미세한 전기 자극이 뇌 기능 조절에 유용하다는 것이 과학적으로 밝혀졌습니다. 이처럼 미세한 전기는 각 질환과 관련된 주요 뇌 부위에 적용함으로써 뇌 기능의 정상화에 효과를 보입니다. 
  
  와이브레인은 이러한 기술을 기반으로 만들어진 의료기기 MINDD가 우울증 치료에 도움이 된다는 것을 대규모 임상 연구를 통해 입증하였습니다.`,

  'technologMechanismySubject1': '우울증이란?',
  'technologMechanismyContents1': '심각한 우울증환자는 다음과 같이 호소합니다.',
  'technologMechanismyContents2-1': '“정말 어둠 속에서 발목이 사슬에 붙잡힌 채,',
  'technologMechanismyContents2-2': '가슴에 거대한 쇳덩이를 매달고 고꾸라질 것 같은 몸을 억지로 추스르며',
  'technologMechanismyContents2-3': '공포에 떤 채로 걷는 것 같다.',
  'technologMechanismyContents3': '우울증에 동반되는 증상들은 식욕이나 성욕 저하와 같은 기본적인 생활에 지장을 줄 뿐만 아니라 기억력이나 집중력 감퇴와 같은 인지 능력 저하, 그리고 호르몬과 면역 체계 불균형과 같은 신체 기능 악화까지도 영향을 미칩니다.',
  'technologMechanismyContents4': '일반적으로 마음의 감기라고 알려진 우울증은 감기라는 말처럼 다양한 인지 및 정신적, 신체적 증상으로 일상 기능의 저하를 일으키는 질환으로 생물학 / 심리학 / 사회적 다방면에 걸친 원인으로 인해 발병합니다.',
  'technologMechanismyContents5': '뇌의 거름이라고 알려져 있는 신경전달물질이나 감정, 스트레스 제어와 관련있는 여러가지 뇌 부위에서 제대로 된 작동을 못해서특정한 스트레스에도 견딜 수 없는 큰 괴로움이 지속되는 것으로 알려져 있습니다.이에 따라 사람들은 민감해지고, 불편한 감정을 느끼거나 우울감을 느끼게 됩니다.',
  'technologMechanismySubject2': '•	생화학적 / 환경적 요인들로 인한',
  'technologMechanismyContents6': ': 뇌 항상성 유지 실패 및 호르몬 불균형 유발',
  'technologMechanismySubject3': '•	신경 전달물질 조절 작용 문제',
  'technologMechanismyContents7': ': 뇌 기능 조절 및 감정 제어 실패',
  'technologMechanismySubject4': '• 좌 / 우측 전전두엽의 비대칭화',
  'technologMechanismyContents8': ': 스트레스와 불편한 상황에 고착화',
  'technologMechanismySubject5': '• 전대상피질, 편도체의 과활성화',
  'technologMechanismyContents9': ': 감정 제어 문제',
  'technologMechanismySubject6': '• 해마 / 시상하부 등의 비활성화',
  'technologMechanismyContents10': ': 수면, 기억력 저하',
  'technologMechanismySubject7': '우울증 치료',
  'technologMechanismyContents11': '우울증은 치료가 충분히 가능한 질병입니다. 그러나 일시적인 감정으로 받아들여 오랜시간 방관하게 되거나 사회적인 시선과 편견때문에 본인 스스로 위축되는 일들이 많아 스트레스가 쌓이게 되고 뇌 기능은 더욱 저하됩니다. 이에 따라 우울증은 스스로 치유할 수 없는 상태의 중증으로 악화됩니다.',
  'technologMechanismyContents12': '따라서 상황이 더 악화되기 전에 주변의 도움은 물론, 정신건강 전문가의 조언에 따라 우울증을 치료하고 관리하는 것이 매우 중요합니다. 심리적 상태와 우울증의 유형에 따라 의사선생님은 항우울제나 수면제와 같은 약물 치료부터 상담치료나 심리치료와 같은 다양한 방법의 치료를 진행합니다.',
  'technologMechanismyContents13': '• 	생물학적 관점',
  'technologMechanismyContents14': '• 	신경 호르몬 불균형 치료 중점',
  'technologMechanismyContents15': '• 	심리학적 관점',
  'technologMechanismyContents16': '• 	심리적 및 사회적 요소 해소 중점',
  'technologMechanismyContents17': '• 	신경생리학적 관점',
  'technologMechanismyContents18': '• 	비정상적 신경활동 재활 중점',
  'technologMechanismyContents19': '미세한 전류 자극을 통한 국부적인 뇌 기능 조절 치료는 기존의 치료법의 효능 한계와 부작용의 단점을 보완할 수 있으며 보다 다양한 치료 옵션의 제공을 가능케 합니다.',
  'technologyCiraContents1': '•    피부 접촉 자동 인식',
  'technologyCiraContents2': '•    연속 임피던스 모니터링',
  'technologyCiraContents3': '•    처방 및 순응도 관리 시스템',

  'productPurposeSubject1': '우울증 치료기기 ‘MINDD’',
  'productPurposeContents1': '경두개 전기 자극 기술을 사용화한 제품으로 미세한 전기 자극을 통해',
  'productPurposeContents2': '뇌 신경을 조절, 우울증과 같은 정신 질환을 개선해주는 제품입니다.',
  'productPurposeSubject2': '환자에게 보다 가치있는 치료를 제공합니다.',
  'productPurposeContents3': '실제 정신질환이 있는 환자들에게 보다 가치있는 치료를 제공하기위해',
  'productPurposeContents4': '매 순간 실제 의료 현장에서 부족한 부분을 찾아내고, 끊임없이 연구하고 개발합니다.',
  'productEsSubject1': '안전성',
  'productEsContents1': '국내에서 연구, 개발, 생산을 한 제품으로 국내 메이저 대학병원 7곳에서 96명을 대상으로 직접 허가 임상을 실시한 제품이므로 안전성과 효능성 모두 입증받았습니다.',
  'productEsSubject2': '신뢰성',
  'productEsContents2': '제품 ‘MINDD’ 는 저희 와이브레인에서 연구, 개발, 생산을 모두 진행합니다. 카이스트 출신의 석/박사 및 뇌공학박사, 의료전문가 등 신뢰할 수 있는 전문가들로 구성되어 있습니다. 또한, ‘MIND’ 가 가지고 있는 경두개 전기 자극 기술은 국내뿐만 아니라, 해외에서도 많은 연구와 임상이 이루어진 기술로서 이에 대한 신뢰성은 이미 국내외로 모두 입증되어있습니다.',
  'productUseLegal': '※ 이 제품은 "의료기기"이며, "사용상의 주의사항"과 "사용방법"을 잘 읽고 사용하십시오. (허가번호 : 제허 17-135호)',

}
